#!/bin/bash
# Builds the Companion module package (castika-deckshow-<ver>.tgz) exactly the
# way Bitfocus builds a module from its repository: yarn install + yarn package.
#
# This folder is laid out like bitfocus/companion-module-template-js so it can be
# pushed to bitfocus/companion-module-castika-deckshow as is. The only generated
# file it carries is src/key_icon.js (the key icon as base64, taken from the
# Stream Deck plugin's key@2x.png); this script refreshes it in place so the
# module keeps building on its own.
#
# Builds never run inside the source folder: the folder is copied to
# $DECKSHOW_BUILD_DIR/companion-module (default ~/deckshow-build/...), yarn runs
# there, and only the finished .tgz (to the package root's companion/) and the
# yarn.lock (kept next to package.json, as Bitfocus expects) come back.
set -euo pipefail
SRC="$(cd "$(dirname "$0")" && pwd -P)"
ROOT="$(dirname "$(dirname "$SRC")")"  # dev/companion-module -> package root
BUILD="${DECKSHOW_BUILD_DIR:-$HOME/deckshow-build}/companion-module"
ICON="$ROOT/streamdeck/com.castika.deckshow.sdPlugin/imgs/actions/key/key@2x.png"
YARN="npx --yes @yarnpkg/cli-dist@4.17.0"  # yarn 4 without needing corepack on this Mac

{
  echo "// Generated by build.sh from streamdeck/com.castika.deckshow.sdPlugin/imgs/actions/key/key@2x.png"
  echo "// (the idle icon of a placed key, same as the Stream Deck plugin's). Do not edit by hand."
  printf "module.exports = 'data:image/png;base64,%s'\n" "$(base64 -i "$ICON" | tr -d '\n')"
} > "$SRC/src/key_icon.js"

mkdir -p "$BUILD"
rsync -a --delete --exclude node_modules --exclude pkg --exclude '*.tgz' --exclude .yarn "$SRC/" "$BUILD/"
cd "$BUILD"
$YARN install
rm -f ./*.tgz
$YARN package
VER=$(node -p "require('./package.json').version")
mkdir -p "$ROOT/companion"
rm -f "$ROOT/companion/castika-deckshow-"*.tgz
cp "castika-deckshow-$VER.tgz" "$ROOT/companion/"
cp yarn.lock "$SRC/yarn.lock"
echo "built in $BUILD"
ls -la "$ROOT/companion/"
